sudo: required
services: 
  - docker
script:
  - docker build -t nanocar1926/DockerCI .
  - docker images nanoar1926/DockerCI

before_deploy:
  - docker login -u <nanocar1926> -p <mercado1926>
deploy:
  provider: script
  script: docker push nanocar1926/DockerCI
  on:
    branch: master
